server_name: airpc-e2e-nats
port: 4222
http: 8222

authorization {
  users: [
    {
      user: "edge"
      password: "edge-demo-pass"
      permissions: {
        publish: ["airpc.v1.route.*.unary", "airpc.v1.route.*.open"]
        subscribe: ["_INBOX.>"]
      }
    },
    {
      user: "connector"
      password: "connector-demo-pass"
      permissions: {
        subscribe: ["airpc.v1.route.*.unary", "airpc.v1.route.*.open"]
        publish: ["_INBOX.>"]
      }
    }
  ]
}
